#
#	OSX makefile for pvocex2
#	
#
CC=cc
CPP=g++
#assumes fftw is built and installed in 'the usual place'
INCFFTW = -I$(HOME)/dev/fftw-2.1.5/fftw -I$(HOME)/dev/fftw-2.1.5/rfftw
LPORTSF = -L../lib
IPORTSF = -I../include
FFTWLIBS = -lrfftw -lfftw
#CFLAGS=-Wall -Dunix -DUSE_FFTW -DFFTW_ENABLE_FLOAT $(IPORTSF) $(INCFFTW)
CFLAGS= -Wall -Dunix -arch x86_64 -mmacosx-version-min=10.9 -I../include $(IPORTSF)
PROG = pvocex2
BINS=pvocex2.o oscbank.o pvoc.o mxfft.o

.c.o:
	$(CC) $(CFLAGS) -c $<
.cpp.o:
	$(CPP) $(CFLAGS) -c $<
#
#	targets
#
all:	$(PROG)

clean:
	rm -f $(PROG)

veryclean:	clean
	rm -f $(BINS)

$(PROG):	$(BINS)
	$(CPP) $(CFLAGS) $(BINS) -o $(PROG) $(LPORTSF) -luportsf -lupvxio -lm -lstdc++

install:	 $(PROG)
	cp $(PROG) ../Release	
#
#	dependencies
#
oscbank.o:	oscbank.h
pvoc.o pvocex2.o:	pvpp.h
