# Mingw makefile for pvxio 

CC = gcc
OPT = -O3
#OPT = -g

CFLAGS = $(OPT) -D_X86_ -DWIN32 -D_WIN32 -D__GNUWIN32__  -Wall -Werror=strict-aliasing -I../include
OBJS=pvfileio.o
TARGET=libpvxio.a

.c.o:
	$(CC) $(CFLAGS) -c $<

all:	$(TARGET)

	 
$(TARGET): $(OBJS)
	ar cr  -o $(TARGET) $(OBJS)
	ranlib $(TARGET)

clean:
	rm  -f $(OBJS)

veryclean:	clean
	rm -f $(TARGET)

install:	$(TARGET)
	cp $(TARGET) ../lib
    
# dependencies

pvfileio.o:	../include/pvfileio.h ../include/pvdefs.h




