#
#	OSX makefile for portsf © Richard Dobson, CDP Ltd 2014
#

#
CC=gcc
CFLAGS=-O2  -I../include
PSFOBJS=portsf.o ieee80.o
TARGET=libportsf.a

.c.o:
	$(CC) $(CFLAGS) -c $<
#
#	targets
#

all:	$(TARGET)

clean:
	rm -f  $(PSFOBJS)

veryclean:	clean
	rm -f  $(TARGET)

$(TARGET):	$(PSFOBJS)
	ar cr -o $(TARGET) $(PSFOBJS)
	ranlib $(TARGET)

install:	$(TARGET)
	cp $(TARGET) ../lib

#
#	dependencies
#
portsf.o:	../include/portsf.h ieee80.h


